Repository primesearch/mfaktc, pull requests merged in 2025-09, with the labels that each got.

#70 clean up `--help` output
  README.txt
  src/cuda_utils.cu
  src/output.c
  src/params.h
Labels: enhancement

#72 Unique random temp file name
  Changelog.txt
  src/filelocking.c
  src/filelocking.h
  src/mfaktc.c
  src/parse.c
Labels: enhancement

#75 Various documentation updates
  .gitignore
  Changelog.txt
  README.txt
  src/filelocking.h
  src/mfaktc.c
  src/mfaktc.ini
  src/parse.c
Labels: documentation

#78 Port documentation and formatting changes from main branch
  .gitignore
  Changelog.txt
  README.txt
  src/mfaktc.ini
  src/output.c
  src/params.h
  src/parse.c
  src/read_config.c
Labels: documentation, enhancement

#79 Implement new timestamp options
  Changelog.txt
  src/mfaktc.ini
  src/my_types.h
  src/output.c
  src/output.h
  src/params.h
  src/parse.c
  src/read_config.c
Labels: enhancement

#83 [0.23] General improvements (2025-09-27)
  Changelog.txt
  src/checkpoint.c
  src/mfaktc.c
  src/mfaktc.ini
  src/my_types.h
  src/output.c
Labels: enhancement

#86 Fix checkpoint reads and reaching max factors
  src/checkpoint.c
  src/mfaktc.c
Labels: bug
