Repository primesearch/mfaktc, pull requests merged in 2025-07, with the labels that each got.

#49 Add Blackwell support to Makefile.win
  src/Makefile.win
Labels: bug

#47 Disambiguate release information
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/scripts/build_helper.sh
  Changelog.txt
  src/mfaktc.ini
Labels: documentation, enhancement

#50 Backport changes to 0.23 branch and bump to version 0.23.5
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/scripts/build_helper.sh
  Changelog.txt
  src/Makefile
  src/Makefile.win
  src/mfaktc.ini
  src/params.h
Labels: bug, documentation, enhancement
